### ISSUE TITLE
Libfdk crashed to encode specific file

### ISSUE THREAD

**Issue by alexpokotilo** [mstorsjo/fdk-aac#60]
Libfdk failed to encode following file
https://drive.google.com/file/d/0B1M0AqE6GJyBNUFEYUlrdDJCUW8/view?usp=sharing

the problem reproduced with our application and with ffmpeg. ffmpeg command line is 

ffmpeg -i 2017-03-11_14:07:11.mkv -vn -c:a libfdk_aac -profile:a aac_he_v2 -b:a 32k 2017-03-11_14:07:11.ts

unfortunately if we cut the file problem not reproduced so please start the command above and wait till encoder move to 00:37:00. As we don't add -re encoder will reach 00:37:00 in two minutes.
then it crash with following stack
ffmpeg: libFDK/src/fixpoint_math.cpp:439: FIXP_DBL invSqrtNorm2(FIXP_DBL, INT*): Assertion `val > (FIXP_DBL)( ( (0.0) >= 0) ? ((( (double)(0.0) * (((INT64(1)<<(32-1)))) + 0.5 ) >= (double)(((signed)0x7FFFFFFF)) ) ? (INT)(((signed)0x7FFFFFFF)) : (INT)( (double)(0.0) * (double)(((INT64(1)<<(32-1)))) + 0.5)) : ((( (double)(0.0) * (((INT64(1)<<(32-1)))) - 0.5) <= (double)(((signed)0x80000000)) ) ? (INT)(((signed)0x80000000)) : (INT)( (double)(0.0) * (double)(((INT64(1)<<(32-1)))) - 0.5)) )' failed.
Aborted (core dumped)

we have the same stack in our application without ffmpeg so it's definitely FDK issue.
If we add -af "volume=0.90" so we modify a little incoming audio stream problem is not reproduced

**Comment by alexpokotilo** [comment]
if we set -profile:a aac_he instead of -profile:a aac_he_v2 problem not reproduced.
So it's probably related to aac_he_v2

**Comment by mstorsjo** [comment]
I'm unable to reproduce this crash - have you tried with the latest release of libfdk-aac? There's been a number of similar looking crashes fixed in the last few releases.

If you still can make it crash with the latest version, then try decoding the audio into some lossless format like flac and uploading that, otherwise the crash can be caused/avoided by local rounding differences in the mp3 decoding.

**Comment by alexpokotilo** [comment]
Martin,
I check this issue with libfdk v0.1.5(latest) and ffmpeg version 3.2.2. 
if you run following command
**ffmpeg -i 2017-03-11_14:07:11.mkv -vn -c:a libfdk_aac -profile:a aac_he_v2 -b:a 32k 2017-03-11_14:07:11.ts**
you will not get crash immediately but need to wait for ~ a minute so ffmpeg time will be about 00:37:00.

My ffmpeg build script is 
./configure --extra-cflags="-I/home/alex/Development/fdk-aac/ffmpeg_build/include/" --extra-ldflags="-L/home/alex/Development/fdk-aac/ffmpeg_build/lib/" --enable-libfdk-aac --enable-pic --enable-decoder=libfdk_aac --enable-encoder=libfdk_aac --enable-libspeex --disable-yasm --enable-pic
make -j 4

yasm disabled here but I've checked and with enabled yasm I have the same issue.

**If you still can make it crash with the latest version, then try decoding the audio into some lossless format like flac and uploading that, otherwise the crash can be caused/avoided by local rounding differences in the mp3 decoding.**
problem reproduced on several different machines so I don't think rounding is a problem here but I've converted to flac and tested with it. Crash reproduced as well. Here is a link to [2017-03-11_14:07:11.flac](https://drive.google.com/file/d/0B1M0AqE6GJyBVzlQWDdSTG9iRms/view?usp=sharing)


ffmpeg -i 2017-03-11_14:07:11.flac -vn -c:a libfdk_aac -profile:a aac_he_v2 -b:a 32k 2017-03-11_14:07:11.ts
ffmpeg version 3.2.2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
  configuration: --extra-cflags='-I/home/alex/Development/fdk-aac/ffmpeg_build/include/ -I/home/alex/Development/libx264/x264-snapshot-20161124-2245-stable/ffmpeg_build/include' --extra-ldflags='-L/home/alex/Development/fdk-aac/ffmpeg_build/lib/ -L/home/alex/Development/libx264/x264-snapshot-20161124-2245-stable/ffmpeg_build/lib/' --enable-libfdk-aac --enable-pic --enable-decoder=libfdk_aac --enable-encoder=libfdk_aac --enable-libspeex --disable-yasm --enable-gpl --enable-libx264 --enable-nonfree --enable-static --extra-libs=-ldl --disable-optimizations --disable-mmx --disable-stripping
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Input #0, flac, from '2017-03-11_14:07:11.flac':
  Metadata:
    STREAMTITLE     : Positively Laughing - Brighten Your day with positivityradio world p2
    ICY-NOTICE1     : <BR>This stream requires <a href="http://www.winamp.com">Winamp</a><BR>
    ICY-NOTICE2     : SHOUTcast DNAS/posix(linux x64) v2.4.7.256<BR>
    ICY-NAME        : Positively Laughing
    ICY-GENRE       : Talk
    ICY-BRE         : 128
    ICY-URL         : http://www.positivityradio.world
    ICY-PUB         : 1
    ENCODER         : Lavf57.56.100
  Duration: 01:00:15.06, start: 0.000000, bitrate: 632 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
File '2017-03-11_14:07:11.ts' already exists. Overwrite ? [y/N] y
[mpegts @ 0x4059240] frame size not set
Output #0, mpegts, to '2017-03-11_14:07:11.ts':
  Metadata:
    STREAMTITLE     : Positively Laughing - Brighten Your day with positivityradio world p2
    ICY-NOTICE1     : <BR>This stream requires <a href="http://www.winamp.com">Winamp</a><BR>
    ICY-NOTICE2     : SHOUTcast DNAS/posix(linux x64) v2.4.7.256<BR>
    ICY-NAME        : Positively Laughing
    ICY-GENRE       : Talk
    ICY-BRE         : 128
    ICY-URL         : http://www.positivityradio.world
    ICY-PUB         : 1
    encoder         : Lavf57.56.100
    Stream #0:0: Audio: aac (libfdk_aac) (HE-AACv2), 44100 Hz, stereo, s16, 32 kb/s
    Metadata:
      encoder         : Lavc57.64.101 libfdk_aac
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
ffmpeg: libFDK/src/fixpoint_math.cpp:439: FIXP_DBL invSqrtNorm2(FIXP_DBL, INT*): Assertion `val > (FIXP_DBL)( ( (0.0) >= 0) ? ((( (double)(0.0) * (((INT64(1)<<(32-1)))) + 0.5 ) >= (double)(((signed)0x7FFFFFFF)) ) ? (INT)(((signed)0x7FFFFFFF)) : (INT)( (double)(0.0) * (double)(((INT64(1)<<(32-1)))) + 0.5)) : ((( (double)(0.0) * (((INT64(1)<<(32-1)))) - 0.5) <= (double)(((signed)0x80000000)) ) ? (INT)(((signed)0x80000000)) : (INT)( (double)(0.0) * (double)(((INT64(1)<<(32-1)))) - 0.5)) )' failed.
Aborted (core dumped)

**Comment by mstorsjo** [comment]
Sorry, I accidentally tested an older version myself - now I'm able to reproduce the issue. I'll have a look into it.

**Comment by mstorsjo** [comment]
This particular crash is fixed on master now.

**Comment by alexpokotilo** [comment]
Thanks a lot ! Could you please shed some light about what it was and how to prevent such cases ?

**Comment by mstorsjo** [comment]
The issue basically was that some coefficients, that were summed, overflowed the expected range of the number. Often this can happen for "unexpected" sounds, like pops/clicks (some times due to a broken input sound, but also possible for completely normal sounds). It's reallly hard to prevent unfortunately - the only help is to use the encoder more and report all cases where crashes are encountered. I guess the AAC-LC mode is the most used, so that will probably have the smallest probability of running into issues like this.

**Comment by alexpokotilo** [comment]
Hi,
I've performed checkout to code with fix
git checkout 5eb6f0db8cc1ecc00af2ef534078e4c65fdf978f
rebuild ffmpeg and issue is still here.
Could you please confirm 5eb6f0db8cc1ecc00af2ef534078e4c65fdf978f revision is fine and issue not reproduced for you ?

**Comment by mstorsjo** [comment]
Yes, I can confirm that the issue isn't reproduced any longer after commit 5eb6f0d, with the exact command line that you provided, with the file you provided. If you still can reproduce it, it's either a different issue (which only happens on some systems), or the new version of fdk-aac actually didn't end up being taken into use.

**Comment by alexpokotilo** [comment]
Martin,
Am sorry this time I probably missed something during rebuild. I confirm it really works fine.
